nations_fifa = [
    # country, continent, population, capital, stability, corruption, fanbase level, name generator
    ['Afghanistan', 'Asia', 37172386, 'Kabul', 'volatile', 'high', 'low', ['fa_IR']],
    ['Albania', 'Europe', 2866376, 'Tirana', 'calm', 'high', 'high', ['tr_TR']],
    ['Algeria', 'Africa', 42228429, 'Algiers', 'moderate', 'high', 'high', ['ar_AA']],
    ['Andorra', 'Europe', 77006, 'Andorra la Vella', 'calm', 'low', 'low', ['es_ES']],
    ['Angola', 'Africa', 30809762, 'Luanda', 'moderate', 'high', 'high', ['pt_PT', 'tw_GH']],
    ['Antigua and Barbuda', 'North America', 96286,
        "Saint John's", 'calm', 'low', 'low', ['en_US']],
    ['Argentina', 'South America', 44494502,
        'Buenos Aires', 'volatile', 'high', 'high', ['es_ES', 'es_MX', 'es_CO', ]],
    ['Armenia', 'Europe', 2951776, 'Yerevan', 'moderate', 'high', 'high', ['hy_AM']],
    ['Australia', 'Asia', 24992369, 'Canberra', 'calm', 'low', 'moderate', ['en_NZ', 'en_GB']],
    ['Austria', 'Europe', 8847037, 'Vienna', 'calm', 'low', 'high', ['de_AT', 'de_DE']],
    ['Azerbaijan', 'Europe', 9942334, 'Baku', 'moderate', 'high', 'moderate', ['az_AZ']],
    ['Bahamas', 'North America', 385640, 'Nassau', 'calm', 'low', 'low', ['en_US']],
    ['Bahrain', 'Asia', 1569439, 'Manama', 'calm', 'low', 'low', ['ar_AA']],
    ['Bangladesh', 'Asia', 164689383, 'Dhaka', 'volatile', 'high', 'low', ['bn_BD']],
    ['Barbados', 'North America', 286641, 'Bridgetown', 'calm', 'low', 'low', ['en_US']],
    ['Belarus', 'Europe', 9449323, 'Minsk', 'volatile', 'high', 'moderate', ['ru_RU']],
    ['Belgium', 'Europe', 11319511, 'Brussels', 'calm', 'low', 'high', ['nl_NL', 'fr_FR']],
    ['Belize', 'North America', 383071, 'Belmopan', 'calm', 'low', 'low', ['en_US']],
    ['Benin', 'Africa', 11485048, 'Porto-Novo', 'moderate', 'high', 'high', ['fr_FR', 'tw_GH']],
    ['Bhutan', 'Asia', 807610, 'Thimphu', 'calm', 'low', 'low', 'en_IN'],
    ['Bolivia', 'South America', 11353142, 'Sucre', 'moderate', 'high', 'high', ['es_ES', 'es_MX', 'es_CO', ]],
    ['Bosnia and Herzegovina', 'Europe', 3280819,
        'Sarajevo', 'volatile', 'high', 'high', ['hr_HR', 'tr_TR']],
    ['Botswana', 'Africa', 2351627, 'Gaborone', 'calm', 'low', 'low', ['tw_GH', 'de_DE', 'en_US']],
    ['Brazil', 'South America', 209469333, 'Brasília', 'moderate', 'high', 'high', ['pt_BR']],
    ['Brunei', 'Asia', 428962, 'Bandar Seri Begawan', 'moderate', 'high', 'low', ['or_IN']],
    ['Bulgaria', 'Europe', 6948445, 'Sofia', 'volatile', 'high', 'high', ['bg_BG']],
    ['Burkina Faso', 'Africa', 19751535, 'Ouagadougou', 'moderate', 'high', 'high', ['fr_FR', 'tw_GH']],
    ['Burundi', 'Africa', 11890784, 'Bujumbura', 'moderate', 'high', 'high', ['fr_FR', 'tw_GH']],
    ['Cabo Verde', 'Africa', 555987, 'Praia', 'calm', 'low', 'high', ['pt_PT', 'tw_GH', 'pt_BR']],
    ['Cambodia', 'Asia', 16249798, 'Phnom Penh', 'moderate', 'high', 'low', ['en_TH']],
    ['Cameroon', 'Africa', 26545864, 'Yaoundé', 'moderate', 'high', 'high', ['fr_FR', 'tw_GH']],
    ['Canada', 'North America', 37058856, 'Ottawa', 'calm', 'low', 'moderate', ['en_CA', 'en_US']],
    ['Central African Republic', 'Africa', 4659080,
        'Bangui', 'moderate', 'high', 'high', ['fr_FR', 'tw_GH']],
    ['Chad', 'Africa', 15477751, "N'Djamena", 'moderate', 'high', 'high', ['fr_FR', 'tw_GH']],
    ['Chile', 'South America', 18191900, 'Santiago', 'volatile', 'high', 'high', ['es_ES', 'es_MX', 'es_CO', ]],
    ['China', 'Asia', 1392730000, 'Beijing', 'moderate', 'high', 'low', ['zh_CN']],
    ['Colombia', 'South America', 49648685, 'Bogotá', 'moderate', 'high', 'high', ['es_CO']],
    ['Comoros', 'Africa', 869601, 'Moroni', 'moderate', 'high', 'high', ['fr_FR', 'tw_GH']],
    ['Republic of the Congo', 'Africa', 5260750,
        'Brazzaville', 'moderate', 'high', 'high', ['fr_FR', 'tw_GH']],
    ['Democratic Republic of the Congo', 'Africa',
        86790567, 'Kinshasa', 'moderate', 'high', 'high', ['fr_FR', 'tw_GH']],
    ['Costa Rica', 'North America', 4999441, 'San José', 'calm', 'low', 'high', ['es_ES', 'es_MX', 'es_CO', ]],
    ["Côte d'Ivoire", 'Africa', 26378274,
        'Yamoussoukro', 'moderate', 'high', 'high', ['fr_FR', 'tw_GH']],
    ['Croatia', 'Europe', 4105267, 'Zagreb', 'volatile', 'high', 'high', ['hr_HR']],
    ['Cuba', 'North America', 11326616, 'Havana', 'volatile', 'high', 'high', ['es_ES', 'es_MX', 'es_CO', ]],
    ['Cyprus', 'Europe', 1207359, 'Nicosia', 'moderate', 'high', 'high', ['el_GR']],
    ['Czech Republic', 'Europe', 10629928, 'Prague', 'calm', 'low', 'high', ['cs_CZ']],
    ['Denmark', 'Europe', 5792202, 'Copenhagen', 'calm', 'low', 'high', ['da_DK']],
    ['Djibouti', 'Africa', 988000, 'Djibouti', 'moderate', 'high', 'low', ['fr_FR', 'tw_GH']],
    ['Dominica', 'North America', 71986, 'Roseau', 'calm', 'low', 'low', ['en_US', 'es_ES', 'es_MX', 'es_CO', ]],
    ['Dominican Republic', 'North America', 10847910,
        'Santo Domingo', 'moderate', 'high', 'high', ['es_ES', 'es_MX', 'es_CO', ]],
    ['Ecuador', 'South America', 17643054, 'Quito', 'moderate', 'high', 'high', ['es_ES', 'es_MX', 'es_CO', ]],
    ['Egypt', 'Africa', 98423595, 'Cairo', 'volatile', 'high', 'high', ['ar_AA']],
    ['El Salvador', 'North America', 6486205,
        'San Salvador', 'moderate', 'high', 'high', ['es_ES', 'es_MX', 'es_CO', ]],
    ['Equatorial Guinea', 'Africa', 1308974, 'Malabo', 'moderate', 'high', 'high', ['tw_GH', 'es_ES']],
    ['Eritrea', 'Africa', 3546421, 'Asmara', 'volatile', 'high', 'high', ['ar_AA']],
    ['Estonia', 'Europe', 1326535, 'Tallinn', 'calm', 'low', 'moderate', ['et_EE']],
    ['Eswatini', 'Africa', 1160164, 'Mbabane', 'calm', 'low', 'low', ['en_GB', 'tw_GH', 'en_US']],
    ['Ethiopia', 'Africa', 114963588, 'Addis Ababa', 'volatile', 'high', 'low', ['ar_AA', 'he_IL']],
    ['Fiji', 'Oceania', 896445, 'Suva', 'moderate', 'high', 'low', ['en_US', 'en_GB']],
    ['Finland', 'Europe', 5540720, 'Helsinki', 'calm', 'low', 'high', ['fi_FI']],
    ['France', 'Europe', 65273511, 'Paris', 'calm', 'low', 'high', ['fr_FR']],
    ['Gabon', 'Africa', 2119275, 'Libreville', 'moderate', 'high', 'high', ['fr_FR', 'tw_GH']],
    ['Gambia', 'Africa', 2416668, 'Banjul', 'moderate', 'high', 'high', ['fr_FR', 'tw_GH']],
    ['Georgia', 'Europe', 3989167, 'Tbilisi', 'volatile', 'high', 'high', ['ka_GE']],
    ['Germany', 'Europe', 83783942, 'Berlin', 'calm', 'low', 'high', ['de_DE']],
    ['Ghana', 'Africa', 31072940, 'Accra', 'moderate', 'high', 'high', ['en_GB', 'tw_GH', 'en_US']],
    ['Greece', 'Europe', 10423054, 'Athens', 'volatile', 'high', 'high', ['el_GR']],
    ['Grenada', 'North America', 112523, "St. George's", 'calm', 'low', 'low', ['en_US', 'es_ES', 'es_MX', 'es_CO', ]],
    ['Guatemala', 'North America', 17915568,
        'Guatemala City', 'moderate', 'high', 'high', ['es_ES', 'es_MX', 'es_CO', ]],
    ['Guinea', 'Africa', 13132795, 'Conakry', 'moderate', 'high', 'high', ['fr_FR', 'tw_GH']],
    ['Guinea-Bissau', 'Africa', 1968001, 'Bissau', 'moderate', 'high', 'high', ['fr_FR', 'tw_GH']],
    ['Guyana', 'South America', 786552, 'Georgetown', 'moderate', 'high', 'high', ['en_US', 'en_GB', 'fr_FR']],
    ['Haiti', 'North America', 11402528,
        'Port-au-Prince', 'volatile', 'high', 'high', ['es_ES', 'fr_FR']],
    ['Honduras', 'North America', 9904607,
        'Tegucigalpa', 'moderate', 'high', 'high', ['es_ES', 'es_MX', 'es_CO', ]],
    ['Hungary', 'Europe', 9660351, 'Budapest', 'volatile', 'high', 'high', ['hu_HU']],
    ['Iceland', 'Europe', 341243, 'Reykjavík', 'calm', 'low', 'high', ['sv_SE']],
    ['India', 'Asia', 1380004385, 'New Delhi', 'volatile', 'high', 'low', ['en_IN']],
    ['Indonesia', 'Asia', 273523615, 'Jakarta', 'volatile', 'high', 'low', ['id_ID']],
    ['Iran', 'Asia', 83992949, 'Tehran', 'volatile', 'high', 'high', ['fa_IR']],
    ['Iraq', 'Asia', 40222493, 'Baghdad', 'volatile', 'high', 'low', ['ar_AA']],
    ['Ireland', 'Europe', 4937786, 'Dublin', 'calm', 'low', 'high', ['en_IE']],
    ['Israel', 'Europe', 8655535, 'Jerusalem', 'volatile', 'high', 'high', ['he_IL']],
    ['Italy', 'Europe', 60461826, 'Rome', 'moderate', 'high', 'high', ['it_IT']],
    ['Jamaica', 'North America', 2961167, 'Kingston', 'moderate', 'high', 'high', ['en_US', 'en_GB', 'es_ES', 'es_MX', 'es_CO', ]],
    ['Japan', 'Asia', 126476461, 'Tokyo', 'moderate', 'high', 'high', ['ja_JP']],
    ['Jordan', 'Asia', 10203134, 'Amman', 'volatile', 'high', 'high', ['ar_AA']],
    ['Kazakhstan', 'Asia', 18776707, 'Astana', 'volatile', 'high', 'high', ['ru_RU']],
    ['Kenya', 'Africa', 53771296, 'Nairobi', 'volatile', 'high', 'high', ['en_GB', 'tw_GH', 'en_US']],
    ['Kiribati', 'Oceania', 119449, 'South Tarawa', 'calm', 'low', 'low', ['en_US', 'en_GB']],
    ['Kosovo', 'Europe', 1895250, 'Pristina', 'volatile', 'high', 'high', ['hr_HR', 'tr_TR']],
    ['Kuwait', 'Asia', 4270571, 'Kuwait City', 'volatile', 'high', 'high', ['ar_AA']],
    ['Kyrgyzstan', 'Asia', 6524195, 'Bishkek', 'moderate', 'high', 'high', ['ru_RU']],
    ['Laos', 'Asia', 7275560, 'Vientiane', 'moderate', 'high', 'high', ['id_ID']],
    ['Latvia', 'Europe', 1886198, 'Riga', 'calm', 'low', 'low', ['lv_LV']],
    ['Lebanon', 'Asia', 6825445, 'Beirut', 'volatile', 'high', 'moderate', ['ar_AA']],
    ['Lesotho', 'Africa', 2142249, 'Maseru', 'moderate', 'high', 'high', ['en_GB', 'tw_GH', 'en_US']],
    ['Liberia', 'Africa', 5057681, 'Monrovia', 'moderate', 'high', 'high', ['en_GB', 'tw_GH', 'en_US']],
    ['Libya', 'Africa', 6871292, 'Tripoli', 'volatile', 'high', 'high', ['ar_AA']],
    ['Liechtenstein', 'Europe', 38128, 'Vaduz', 'calm', 'low', 'low', ['de_DE']],
    ['Lithuania', 'Europe', 2722289, 'Vilnius', 'calm', 'low', 'low', ['lt_LT']],
    ['Luxembourg', 'Europe', 625978, 'Luxembourg', 'calm', 'low', 'high', ['de_DE']],
    ['Madagascar', 'Africa', 27691018, 'Antananarivo', 'volatile', 'high', 'high', ['pt_PT', 'tw_GH']],
    ['Malawi', 'Africa', 19129952, 'Lilongwe', 'volatile', 'high', 'low', ['en_GB', 'tw_GH', 'en_US']],
    ['Malaysia', 'Asia', 32365999, 'Kuala Lumpur', 'moderate', 'high', 'low', ['zh_CN', 'zh_TW', 'en_IN', 'id_ID']],
    ['Maldives', 'Asia', 540544, 'Malé', 'moderate', 'high', 'low', ['en_US', 'en_GB']],
    ['Mali', 'Africa', 20250833, 'Bamako', 'volatile', 'high', 'high', ['fr_FR', 'tw_GH', 'ar_AA']],
    ['Malta', 'Europe', 441543, 'Valletta', 'calm', 'low', 'high', ['en_GB', 'it_IT']],
    ['Marshall Islands', 'Oceania', 59190, 'Majuro', 'calm', 'low', 'low', ['en_US', 'en_GB']],
    ['Mauritania', 'Africa', 4649658, 'Nouakchott', 'volatile', 'high', 'high', ['ar_AA']],
    ['Mauritius', 'Africa', 1271768, 'Port Louis', 'calm', 'low', 'low', ['en_IN']],
    ['Mexico', 'North America', 128932753,
        'Mexico City', 'moderate', 'high', 'high', ['es_MX']],
    ['Micronesia', 'Oceania', 548914, 'Palikir', 'calm', 'low', 'low', ['en_US', 'en_GB']],
    ['Moldova', 'Europe', 4033963, 'Chișinău', 'volatile', 'high', 'high', ['ro_RO']],
    ['Monaco', 'Europe', 39242, 'Monaco', 'calm', 'low', 'low', ['fr_FR']],
    ['Mongolia', 'Asia', 3278290, 'Ulan Bator', 'moderate', 'high', 'moderate', ['ru_RU']],
    ['Montenegro', 'Europe', 628066, 'Podgorica', 'calm', 'low', 'high', ['hr_HR']],
    ['Morocco', 'Africa', 36910560, 'Rabat', 'volatile', 'high', 'high', ['ar_AA']],
    ['Mozambique', 'Africa', 31255435, 'Maputo', 'volatile', 'high', 'high', ['pt_PT', 'tw_GH']],
    ['Myanmar', 'Asia', 54409800, 'Naypyidaw', 'volatile', 'high', 'low', ['id_ID']],
    ['Namibia', 'Africa', 2540905, 'Windhoek', 'moderate', 'high', 'low', ['en_GB', 'tw_GH', 'en_US']],
    ['Nauru', 'Oceania', 10824, 'Yaren District', 'calm', 'low', 'low', ['en_US', 'en_GB']],
    ['Nepal', 'Asia', 29136808, 'Kathmandu', 'volatile', 'high', 'high', ['ne_NP']],
    ['Netherlands', 'Europe', 17134872, 'Amsterdam', 'calm', 'low', 'high', ['nl_NL']],
    ['New Zealand', 'Oceania', 4822233, 'Wellington', 'calm', 'low', 'low', ['en_NZ']],
    ['Nicaragua', 'North America', 6624554, 'Managua', 'moderate', 'high', 'high', ['es_MX', 'es_ES']],
    ['Niger', 'Africa', 24206644, 'Niamey', 'volatile', 'high', 'high', ['fr_FR', 'tw_GH', 'ar_AA']],
    ['Nigeria', 'Africa', 206139587, 'Abuja', 'volatile', 'high', 'high', ['en_GB', 'tw_GH', 'en_US']],
    ['North Korea', 'Asia', 25778816, 'Pyongyang', 'volatile', 'high', 'low', ['ko_KR']],
    ['North Macedonia', 'Europe', 2083374, 'Skopje', 'volatile', 'high', 'high', ['sl_SI']],
    ['Norway', 'Europe', 5421241, 'Oslo', 'calm', 'low', 'high', ['no_NO']],
    ['Oman', 'Asia', 5106626, 'Muscat', 'volatile', 'high', 'low', ['ar_AA']],
    ['Pakistan', 'Asia', 220892340, 'Islamabad', 'volatile', 'high', 'low', ['en_IN']],
    ['Palau', 'Oceania', 18094, 'Ngerulmud', 'calm', 'low', 'low', ['en_US', 'en_GB']],
    ['Panama', 'North America', 4314767,
        'Panama City', 'moderate', 'high', 'moderate', ['es_MX', 'es_ES', 'en_US']],
    ['Papua New Guinea', 'Oceania', 8947024,
        'Port Moresby', 'volatile', 'high', 'low', ['en_US', 'en_GB']],
    ['Paraguay', 'South America', 7132538, 'Asunción', 'moderate', 'high', 'high', ['es_MX', 'es_ES']],
    ['Peru', 'South America', 32971854, 'Lima', 'moderate', 'high', 'high', ['es_MX', 'es_ES', 'es_CO', ]],
    ['Philippines', 'Asia', 109581078, 'Manila', 'volatile', 'high', 'low', ['name', 'en_US', 'last_name', 'es_ES']],
    ['Poland', 'Europe', 37846611, 'Warsaw', 'calm', 'high', 'high', ['pl_PL']],
    ['Portugal', 'Europe', 10196709, 'Lisbon', 'calm', 'low', 'high', ['pt_PT']],
    ['Qatar', 'Asia', 2881053, 'Doha', 'moderate', 'high', 'low', ['ar_AA']],
    ['Romania', 'Europe', 19237691, 'Bucharest', 'volatile', 'high', 'high', ['ro_RO']],
    ['Russia', 'Europe', 145934462, 'Moscow', 'volatile', 'high', 'high', ['ru_RU']],
    ['Rwanda', 'Africa', 12952218, 'Kigali', 'volatile', 'high', 'high', ['fr_FR', 'en_GB', 'en_US']],
    ['Saint Kitts and Nevis', 'North America',
        53199, 'Basseterre', 'calm', 'low', 'low', ['en_US', 'en_GB']],
    ['Saint Lucia', 'North America', 183629, 'Castries', 'calm', 'low', 'low', ['en_US', 'en_GB']],
    ['Saint Vincent and the Grenadines',
        'North America', 110210, 'Kingstown', 'calm', 'low', 'low', ['en_US', 'en_GB']],
    ['Samoa', 'Oceania', 198414, 'Apia', 'calm', 'low', 'low', ['en_US', 'en_GB']],
    ['San Marino', 'Europe', 33931, 'San Marino', 'calm', 'low', 'low', ['it_IT']],
    ['Sao Tome and Principe', 'Africa', 219159, 'São Tomé', 'calm', 'low', 'low', ['pt_PT', 'tw_GH']],
    ['Saudi Arabia', 'Asia', 34813871, 'Riyadh', 'volatile', 'high', 'high', ['ar_AA']],
    ['Senegal', 'Africa', 16743927, 'Dakar', 'volatile', 'high', 'high', ['fr_FR', 'tw_GH', 'en_GB', 'en_US']],
    ['Serbia', 'Europe', 8737371, 'Belgrade', 'volatile', 'high', 'high', ['hr_HR']],
    ['Seychelles', 'Africa', 98347, 'Victoria', 'calm', 'low', 'low', ['fr_FR', 'en_GB', 'en_US']],
    ['Sierra Leone', 'Africa', 7976983, 'Freetown', 'volatile', 'high', 'high', ['en_GB', 'en_US']],
    ['Singapore', 'Asia', 5850342, 'Singapore', 'moderate', 'high', 'low', ['en_US', 'en_GB', 'zh_CN', 'zh_TW', 'en_IN']],
    ['Slovakia', 'Europe', 5459642, 'Bratislava', 'calm', 'low', 'high', ['sl_SI']],
    ['Slovenia', 'Europe', 2078938, 'Ljubljana', 'calm', 'low', 'high', ['sl_SI']],
    ['Solomon Islands', 'Oceania', 686884, 'Honiara', 'calm', 'low', 'low', ['en_US', 'en_GB']],
    ['Somalia', 'Africa', 15893222, 'Mogadishu', 'volatile', 'high', 'high', ['ar_AA']],
    ['South Africa', 'Africa', 59308690, 'Pretoria', 'volatile', 'high', 'high', ['en_GB', 'en_US']],
    ['South Korea', 'Asia', 51269185, 'Seoul', 'volatile', 'high', 'moderate', ['ko_KR']],
    ['South Sudan', 'Africa', 11193725, 'Juba', 'volatile', 'high', 'high', ['en_GB', 'en_US']],
    ['Spain', 'Europe', 46754778, 'Madrid', 'moderate', 'high', 'high', ['es_ES']],
    ['Sri Lanka', 'Asia', 21413249,
        'Sri Jayawardenepura Kotte', 'volatile', 'high', 'low', ['ta_IN']],
    ['Sudan', 'Africa', 43849260, 'Khartoum', 'volatile', 'high', 'high', ['ar_AA']],
    ['Suriname', 'South America', 586632, 'Paramaribo', 'moderate', 'high', 'high', ['nl_NL']],
    ['Sweden', 'Europe', 10099265, 'Stockholm', 'calm', 'low', 'high', ['sv_SE']],
    ['Switzerland', 'Europe', 8654622, 'Bern', 'calm', 'low', 'high', ['de_CH']],
    ['Syria', 'Asia', 17500658, 'Damascus', 'volatile', 'high', 'high', ['ar_AA', 'ar_PS']],
    ['Taiwan', 'Asia', 23816775, 'Taipei', 'volatile', 'high', 'low', ['zh_TW']],
    ['Tajikistan', 'Asia', 9537645, 'Dushanbe', 'volatile', 'high', 'low', ['ru_RU']],
    ['Tanzania', 'Africa', 59734218, 'Dodoma', 'volatile', 'high', 'high', ['en_GB', 'en_US']],
    ['Thailand', 'Asia', 69799978, 'Bangkok', 'moderate', 'high', 'low', ['en_TH']],
    ['Timor-Leste', 'Asia', 1318445, 'Dili', 'volatile', 'high', 'low', ['pt_PT', 'tw_GH']],
    ['Togo', 'Africa', 8278724, 'Lomé', 'volatile', 'high', 'high', ['fr_FR', 'en_GB', 'en_US']],
    ['Tonga', 'Oceania', 105695, "Nuku'alofa", 'calm', 'low', 'low', ['en_US', 'en_GB']],
    ['Trinidad and Tobago', 'North America', 1399488,
        'Port of Spain', 'moderate', 'high', 'low', ['en_US', 'en_GB']],
    ['Tunisia', 'Africa', 11818619, 'Tunis', 'moderate', 'high', 'high', ['ar_AA']],
    ['Turkey', 'Asia', 84339067, 'Ankara', 'volatile', 'high', 'high', ['tr_TR']],
    ['Turkmenistan', 'Asia', 6031200, 'Ashgabat', 'volatile', 'high', 'low', ['ru_RU']],
    ['Tuvalu', 'Oceania', 11792, 'Funafuti', 'calm', 'low', 'low', ['en_US', 'en_GB']],
    ['Uganda', 'Africa', 45741007, 'Kampala', 'volatile', 'high', 'high', ['en_GB', 'en_US']],
    ['Ukraine', 'Europe', 43733762, 'Kyiv', 'war', 'high', 'high', ['uk_UA']],
    ['United Arab Emirates', 'Asia', 9890402,
        'Abu Dhabi', 'moderate', 'high', 'low', ['ar_AA', 'ar_SA']],
    ['United Kingdom', 'Europe', 67886011, 'London', 'moderate', 'high', 'high', ['en_GB']],
    ['United States', 'North America', 331002651,
        'Washington, D.C.', 'moderate', 'high', 'low', ['en_US']],
    ['Uruguay', 'South America', 3473730, 'Montevideo', 'calm', 'low', 'high', ['es_ES']],
    ['Uzbekistan', 'Asia', 33469203, 'Tashkent', 'volatile', 'high', 'low', ['ru_RU']],
    ['Vanuatu', 'Oceania', 307145, 'Port Vila', 'calm', 'low', 'low', ['en_US', 'en_GB']],
    ['Vatican City', 'Europe', 801, 'Vatican City', 'calm', 'low', 'low', ['it_IT']],
    ['Venezuela', 'South America', 28435943,
        'Caracas', 'volatile', 'high', 'high', ['es_ES']],
    ['Vietnam', 'Asia', 97338579, 'Hanoi', 'volatile', 'high', 'low', ['zh_TW']],
    ['Yemen', 'Asia', 29825964, "Sana'a", 'volatile', 'high', 'low', ['ar_SA']],
    ['Zambia', 'Africa', 18383955, 'Lusaka', 'volatile', 'high', 'high', ['en_GB', 'en_US']],
    ['Zimbabwe', 'Africa', 14862927, 'Harare', 'volatile', 'high', 'high', ['en_GB', 'en_US']],
]

derbies = [
    ['Argentina', 'Brazil', 'Battle of the Americas'],
    ['Scotland', 'England', 'The Auld Enemy vs The Tartan Army'],
    ['Germany', 'Netherlands', 'The Oranges vs The Bundesteam'],
    ['Italy', 'Spain', 'The Mediterranean Derby'],
    ['Portugal', 'Spain', 'The Iberian War'],
    ['England', 'Germany', 'The Three Lions vs The Bundesteam'],
    ['Brazil', 'Uruguay', 'The Maracanazo'],
    ['Colombia', 'Venezuela', 'The Derby of the Andes'],
    ['Peru', 'Chile', 'The Clásico del Pacífico'],
    ['Mexico', 'United States', 'El Trí vs The Stars and Stripes'],
    ['Costa Rica', 'Panama', 'The Central American Derby'],
    ['Belgium', 'Netherlands', 'The Low Countries Derby'],
    ['Russia', 'Ukraine', 'The Eastern Derby'],
    ['Poland', 'Czech Republic', 'The Central European Derby'],
    ['Croatia', 'Serbia', 'The Balkans Derby'],
    ['Sweden', 'Denmark', 'The Nordic Derby'],
    ['Norway', 'Sweden', 'The Nordic Derby'],
    ['Finland', 'Sweden', 'The Nordic Derby'],
    ['Slovenia', 'Croatia', 'The Balkans Derby'],
    ['Bosnia and Herzegovina', 'Serbia', 'The Balkans Derby'],
    ['Bulgaria', 'Romania', 'The Balkan Derby'],
    ['Armenia', 'Azerbaijan', 'The Caucasus Derby'],
    ['Armenia', 'Georgia', 'The Caucasus Derby'],
    ['Armenia', 'Turkey', 'The Caucasus Derby'],
    ['Georgia', 'Russia', 'The Caucasus Derby'],
    ['Azerbaijan', 'Turkey', 'The Caucasus Derby'],
    ['Iran', 'Turkey', 'The Middle Eastern Derby'],
    ['Iraq', 'Iran', 'The Middle Eastern Derby'],
    ['Syria', 'Turkey', 'The Middle Eastern Derby'],
    ['Lebanon', 'Syria', 'The Middle Eastern Derby'],
    ['Greece', 'Turkey', 'The Eastern Mediterranean Derby'],
    ['Israel', 'Palestine', 'The Holy Land Derby'],
    ['Australia', 'New Zealand', 'The Trans-Tasman Derby'],
    ['Japan', 'South Korea', 'The East Asian Derby'],
    ['China', 'Japan', 'The East Asian Derby'],
    ['India', 'Pakistan', 'The South Asian Derby'],
    ['Indonesia', 'Malaysia', 'The Southeast Asian Derby'],
    ['Thailand', 'Vietnam', 'The Southeast Asian Derby'],
    ['Cambodia', 'Vietnam', 'The Southeast Asian Derby'],
    ['Laos', 'Thailand', 'The Southeast Asian Derby'],
    ['Myanmar', 'Thailand', 'The Southeast Asian Derby'],
    ['Singapore', 'Malaysia', 'The Southeast Asian Derby'],
    ['Philippines', 'Vietnam', 'The Southeast Asian Derby'],
    ['North Korea', 'South Korea', 'The Korean Derby'],
    ['Canada', 'United States', 'The North American Derby'],
    ['Mexico', 'Canada', 'The North American Derby'],
    ['Cuba', 'Haiti', 'The Caribbean Derby'],
    ['Jamaica', 'Trinidad and Tobago', 'The Caribbean Derby'],
]
